version: "3.9"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=blog
      - POSTGRES_USER=blog
      - POSTGRES_PASSWORD=andrzej123
    ports:
      - "5432:5432"
  web:
    build: .
    command: python ./mysite/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code/
    ports:
      - "8000:8000"
    depends_on:
      - db